# Generated by Django 4.2.23 on 2025-09-15 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('12:00 PM - 1:30 PM', '12:00 PM - 1:30 PM'), ('1.30 PM - 3:00 PM', '1:30 PM - 3:00 PM'), ('3:00 PM - 4:30 PM', '3:00 PM - 4:30 PM'), ('6:00 PM - 7:30 PM', '6:00 PM - 7:30 PM'), ('7:30 PM - 9:00 PM', '7:30 PM - 9:00 PM'), ('9:00 PM - 10:30 PM', '9:00 PM - 10:30 PM')], default='12:00 PM - 1:30 PM', max_length=20)),
                ('number_of_people', models.PositiveIntegerField()),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Completed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_received', to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-booking_date', 'time_slot'],
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', [1, 3])), fields=('user', 'restaurant', 'booking_date', 'time_slot'), name='unique_booking'),
        ),
    ]
