# Generated by Django 4.2.23 on 2025-09-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', 'time_slot']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Confirmed'), (2, 'Cancelled'), (3, 'Completed')], default=1),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('user', 'restaurant', 'booking_date', 'time_slot'), name='unique_booking'),
        ),
    ]
