# Generated by Django 4.2.23 on 2025-09-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_options_alter_booking_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='booking',
            name='unique_booking',
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', [1, 3])), fields=('user', 'restaurant', 'booking_date', 'time_slot'), name='unique_booking'),
        ),
    ]
