# Generated by Django 4.2.23 on 2025-09-08 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_opening_hours_restaurantcarouselimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
    ]
